services:
#    cyb_bot_detect.example:
#        class: Cyberdean\Security\BotDetectBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

 cyb_botdetect.security.listener.request:
        class: Cyberdean\Security\BotDetectBundle\Listener\KernelRequestListener
        arguments: ['@cyb_botdetect.security.manager', '@templating', '@cyb_botdetect.security.configmanager']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 127 }

 cyb_botdetect.security.listener.response:
        class: Cyberdean\Security\BotDetectBundle\Listener\KernelResponseListener
        arguments: ['@doctrine.orm.entity_manager', '@cyb_botdetect.security.configmanager', '@cyb_botdetect.security.manager']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -1 }

# Doctrine Listeners
 cyb_botdetect.security.listener.events:
        class: Cyberdean\Security\BotDetectBundle\Listener\EventsListener
        arguments: ['@event_dispatcher', '@logger']
        tags:
            - { name: doctrine.orm.entity_listener, entity: CybBotDetectBundle\Entity\Security\Strike, event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: CybBotDetectBundle\Entity\Security\Ban, event: prePersist }

# Managers
 cyb_botdetect.security.manager:
        class: Cyberdean\Security\BotDetectBundle\Manager\BotDetectManager
        arguments: ['@doctrine.orm.entity_manager', '@cyb_botdetect.security.configmanager', '@logger', '@event_dispatcher', '@router']

 cyb_botdetect.security.configmanager:
        class: Cyberdean\Security\BotDetectBundle\Manager\ConfigManager
        arguments: []